export const categoryNameSelected = {
  clothes: "ropa",
  electronics: "electronicos",
  "women's%20clothing": "Ropa para dama",
  "men's%20clothing": "Ropa para caballeros",
  jewelery: "Joyeria",
  // "sports and outdoors": "deportes y exteriores",
  // "jewelry and watches": "relojes y joyeria",
  // furniture: "muebles",
  // shoes: "zapatos",
  // fruits: "frutas",
  // "toys and games": "juegos y juguetes",
  // "home and kitchen": "casa y cocina",
  // "health and beauty": "salud y belleza",
  // "books and media": "libros y media",
};
